build: false
shallow_clone: false
platform: 'x86'

install:
  - mkdir PHP
  - cd PHP
  - mkdir 5.3.29
  - cd 5.3.29
  - appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-5.3.29-Win32-VC9-x86.zip
  - 7z x php-5.3.29-Win32-VC9-x86.zip
  - del /Q *.zip
  - cd ../
  - mkdir 5.4.37
  - cd 5.4.37
  - appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-5.4.37-Win32-VC9-x86.zip
  - 7z x php-5.4.37-Win32-VC9-x86.zip
  - del /Q *.zip
  - cd ../
  - mkdir 5.5.21
  - cd 5.5.21
  - appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-5.5.21-Win32-VC11-x86.zip
  - 7z x php-5.5.21-Win32-VC11-x86.zip
  - del /Q *.zip
  - cd ../
  - mkdir 5.6.5
  - cd 5.6.5
  - appveyor DownloadFile http://windows.php.net/downloads/releases/archives/php-5.6.5-Win32-VC11-x86.zip
  - 7z x php-5.6.5-Win32-VC11-x86.zip
  - del /Q *.zip
  - cd ../../

test_script:
  - .\PHP\5.3.29\php.exe .\core\external\wordpress_validator\wordpress_validator.php
  - .\PHP\5.4.37\php.exe .\core\external\wordpress_validator\wordpress_validator.php
  - .\PHP\5.5.21\php.exe .\core\external\wordpress_validator\wordpress_validator.php
  - .\PHP\5.6.5\php.exe .\core\external\wordpress_validator\wordpress_validator.php
